---

apiVersion: "v1"
kind: "ReplicationController"

metadata:
  name: "jenkins"
  labels:
    name: "jenkins"

spec:
  replicas: 1

  template:

    metadata:
      name: "jenkins"
      labels:
        name: "jenkins"

    spec:
      containers:
        - name: "jenkins"
          image: "jenkinsci/jenkins:2.14"

          ports: 
            - containerPort: 8080
            - containerPort: 50000

          volumeMounts: 
            - name: "jenkins-home"
              mountPath: "/var/jenkins_home"

          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          #   initialDelaySeconds: 60
          #   timeoutSeconds: 5

      volumes:
        - name: "jenkins-home"
          gcePersistentDisk:
            pdName: jenkins-home-disk
            fsType: ext4
